# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
      pip3 install -r "/workspace/machine-learning-prework/requirements.txt"
    command: echo 'start script'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9000-9099
    onOpen: ignore

# Install necessary packages
image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - ms-toolsai.jupyter
